Add conversation details
ShokuApp/individual-forward pull request #52
Opened 2021-01-20 08:26 UTC by Mihobsine

Related to [SPAR-279]

[SPAR-279]: https://shokuapp.atlassian.net/browse/SPAR-279

2021-01-20 08:29 UTC, Matttx requested changes

2021-01-20 08:29 UTC, Matttx commented on src/components/messages/connected-user-message.tsx
> +export const ConnectedUserMessage: FC<Props> = (props: Props) => {
Need to change this component in "UserMessage" instead of "ConnectedUserMessage", same for the file

2021-01-24 20:17 UTC, MrSquaare requested changes

2021-01-24 20:17 UTC, MrSquaare commented on src/helpers/messages/get-time.ts
> +export const getTime: (timestamp: number) => string = (timestamp: number) => {
Export this one instead: https://github.com/ShokuApp/individual-forward/blob/a68cb7304a91f16aff8293066f08bc2b0ef5b7ef/src/components/messages/conversation-preview.tsx#L88-#L107

2021-01-26 11:24 UTC, MrSquaare approved these changes

2021-01-27 08:37 UTC, Matttx approved these changes

2021-01-27 20:13 UTC, merged